=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

=end

def fibonacci_sequence (limit)
  sequence = [1, 2]
  total_sum = 2
  last_number = 0
  num = 0
  i = 2
  while total_sum < limit do 
    sequence[i] = sequence[(i-2)] + sequence[(i-1)]
    if sequence[i] % 2 == 0 
      total_sum += sequence[i]
      last_number = sequence[i]
    end
    i += 1
  end
  total_sum = total_sum - last_number
  puts "the total is: #{total_sum}"
end

fibonacci_sequence(4000000)